### ISSUE TITLE
Dynamically changing circle size

### ISSUE THREAD

**Issue by olgunataberk** [olgunataberk/osu#1]
Osu! is a rhythm game. In default play mode (osu!) you need to click the circles that appear on your screen, precisely on the beat, to get the best score. Osu! is the perfect game for people who likes music, clicking and challenging gameplay; as some of the available beatmaps (levels) need a lot of experience to even complete without failing. But since the beatmaps are designed by players, it is hard to find a beatmap for the song you like and even if you find it, the beatmap might be too easy for you.  

Hence we introduce a new feature, DCcR as explained:
- Dynamically changing the radius of the circles (DCcR) that appear on the screen throughout the beatmap and therefore increasing overall difficulty as it would be harder to hit a smaller circle.

  - By letting players choose whether or not to enable DCcR and giving them the ability to customize it, e.g. setting the maximum and minimum length of changing circle radius, we ensure that people can play Osu! the way they want to.

(A small portion of Osu!Normal gameplay)
![Gameplay Gif](https://cloud.githubusercontent.com/assets/22398655/23334796/060fa5f2-fbaf-11e6-8929-56131cc25a9f.gif)

**Comment by cagdasgerede** [comment]
Ok.
