### ISSUE TITLE
DSFB - A less frustrating gameplay.

### ISSUE THREAD

**Issue by olgunataberk** [olgunataberk/osu#2]
In order to get the best score out of a beatmap (level) in Osu! you need to hit all the circles that appear on your screen throughout the whole beatmap. If you miss a circle in the middle of a beatmap, you need to play again from the beginning to get your desired score. This is very frustrating if you keep missing the exact same note, as you will need to play the first half of the beatmap to get to that note.

We introduce a new feature, Do not Start From the Beggining (DSFB), in which:

- If a player fails to pass the beatmap or does not get the score he wants at the end of the beatmap and if the player wants to play again, he can start from the beginning or from the time he made his first miss.

By using this feature, players can also practice the harder sections of a beatmap, without spending much time playing through easier parts.

(A very poor visualization of the proposed feature)
![Osu-Gameplay](https://cloud.githubusercontent.com/assets/22398655/23343800/c043401c-fc79-11e6-93a7-5712d67ed7ba.gif)

**Comment by cagdasgerede** [comment]
ok.

What is the down side of this feature? Do you get less points if you do DSFB?

Is there a limit to this? Do you have only, let's say, 3 chances that you can do this in each section?

**Comment by olgunataberk** [comment]
A score multiplier which decreases with each additional use of DSFB could be introduced as a downside of using DSFB. I believe this could work without limitting the number of uses for DSFB.
